modLoader = "javafml"
loaderVersion = "[2,)"
license = "${license}"
issueTrackerURL = "${issues}"

[[mods]]
modId = "qoh"
logoFile = "icon.png"
version = "${version}"
displayName = "${name}"
authors = "${author}"
credits = "${credits}"
description = '''${description}'''
displayURL = "${home}"


[[dependencies.qoh]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.qoh]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "[${yaci},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.qoh]]
modId = "minecraft"
type = "required"
versionRange = "[${mc_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.qoh]]
modId = "architectury"
type = "required"
versionRange = "[${architectury},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "qoh.mixins.json"